### ISSUE TITLE
BUG: No response received if try to sign in with a non-existant user

### ISSUE THREAD

**Issue by gzinck** [evscott/hackapp-api#48]
Postman hangs with no response when trying to make a sign-in request
```
hackapp-api         | (node:29) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uid' of undefined
hackapp-api         |     at signIn (/usr/src/app/src/handlers/auth.js:121:47)
hackapp-api         |     at <anonymous>
hackapp-api         |     at process._tickCallback (internal/process/next_tick.js:189:7)
hackapp-api         | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
hackapp-api         | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gzinck** [comment]
This is actually a pretty significant problem: the front end just hangs and won't show any error messages to the user.
